"""empty message

Revision ID: acf86bf889a3
Revises: 
Create Date: 2018-04-05 16:24:05.993981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf86bf889a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address_1', sa.String(length=200), nullable=True),
    sa.Column('address_2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=200), nullable=True),
    sa.Column('zip_code', sa.String(length=200), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_email'), 'student', ['email'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address_1', sa.String(length=200), nullable=True),
    sa.Column('address_2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=200), nullable=True),
    sa.Column('zip_code', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('studentprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('school', sa.String(length=64), nullable=True),
    sa.Column('sex', sa.String(length=64), nullable=True),
    sa.Column('age', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=225), nullable=True),
    sa.Column('famsize', sa.String(length=64), nullable=True),
    sa.Column('pstatus', sa.String(length=64), nullable=True),
    sa.Column('medu', sa.String(length=64), nullable=True),
    sa.Column('fedu', sa.String(length=64), nullable=True),
    sa.Column('mjob', sa.String(length=64), nullable=True),
    sa.Column('fjob', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('guardian', sa.String(length=64), nullable=True),
    sa.Column('traveltime', sa.String(length=64), nullable=True),
    sa.Column('studytime', sa.String(length=64), nullable=True),
    sa.Column('failures', sa.String(length=64), nullable=True),
    sa.Column('schoolsup', sa.String(length=64), nullable=True),
    sa.Column('famsup', sa.String(length=64), nullable=True),
    sa.Column('paid', sa.String(length=64), nullable=True),
    sa.Column('activities', sa.String(length=64), nullable=True),
    sa.Column('nursery', sa.String(length=64), nullable=True),
    sa.Column('higher', sa.String(length=64), nullable=True),
    sa.Column('internet', sa.String(length=64), nullable=True),
    sa.Column('romantic', sa.String(length=64), nullable=True),
    sa.Column('famrel', sa.String(length=64), nullable=True),
    sa.Column('freetime', sa.String(length=64), nullable=True),
    sa.Column('goout', sa.String(length=64), nullable=True),
    sa.Column('dalc', sa.String(length=64), nullable=True),
    sa.Column('walc', sa.String(length=64), nullable=True),
    sa.Column('health', sa.String(length=64), nullable=True),
    sa.Column('absences', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentprofile')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_student_email'), table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###
